Repository devs-coffee/frontend-collab-chat-project, pull requests merged in 2023-09, with the labels that each got.

#90 refacto catched errors
  src/components/Auth/Login/Login.tsx
  src/components/Auth/Signup/Signup.tsx
  src/components/ChannelCreationForm/ChannelCreationForm.tsx
  src/components/ChannelUpdateForm/ChannelUpdateForm.tsx
  src/components/DarkModeSwitch/DarkModeSwitch.tsx
  src/components/Message/Message.tsx
  src/components/MessageList/MessageList.tsx
  src/components/ProtectedContent/ProtectedContent.tsx
  src/components/ServerCreationForm/ServerCreationForm.tsx
  src/components/ServerDisplay/ServerMembersBox/ServerMembersBox.tsx
  src/components/ServerSearching/ServerSearching.tsx
  src/components/ServerUpdateForm/ServerUpdateForm.tsx
  src/pages/Profile/Profile.tsx
  src/pages/ServerDisplay/ServerDisplay.tsx
  src/pages/UserDisplay/UserDisplay.tsx
  src/redux/privateChansSlice.ts
  src/redux/serversSlice.ts
  src/services/fetcher.ts
Labels: enhancement

#95 Fix-message-scss
  src/components/MessageList/MessageList.scss
  src/pages/PrivateMessages/PrivateMessages.scss
  src/pages/PrivateMessages/PrivateMessages.tsx
  src/styles/index.scss
Labels: bug, enhancement

#96 implement refresh token
  src/components/Auth/Login/Login.tsx
  src/interfaces/IApiAuthResponse.ts
  src/interfaces/ITokens.ts
  src/interfaces/IUser.ts
  src/redux/authSlice.ts
  src/services/authenticationService.ts
  src/services/fetcher.ts
Labels: enhancement

#99 fix: :package: Fix package missing js-cookie
  package-lock.json
  package.json
Labels: bug
